name: Deploy Production
on:
  push:
    branches:
      - main
jobs:
  deploy_website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: ascend-bf5b2
          channelId: live
          entryPoint: "./demo" # أخبر الروبوت أن يدخل لمجلد demo أولاً
          channelId: live
          entryPoint: "./demo" # يجب أن يكون ملف firebase.json داخل مجلد demo
