name: Deploy to Preview Channel

on:
  pull_request:
    branches:
      - main

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # إضافة خطوات البناء داخل مجلد demo
      - name: Install and Build
        run: |
          cd demo
          npm ci
          npm run build --if-present

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: "ascend-bf5b2"
          
          # التصحيح هنا: الإشارة للمجلد الصحيح
          entryPoint: "./demo"
