name: Deploy to Firebase Hosting
on:
  push:
    branches:
      - main  # سيتم النشر تلقائياً عند أي تعديل على فرع main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # الخطوة الأهم للمشاريع الكبيرة: بناء المشروع
      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      # النشر إلى Firebase
   
      - uses: actions/checkout@v4

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: ascend-bf5b2
          channelId: live
          entryPoint: "demo"
