- uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: ascend-bf5b2
          channelId: live
          entryPoint: "demo"  # تأكد أن هذه القيمة تطابق اسم المجلد تماماً
