name: Deploy Production
on:
  push:
    branches:
      - main
jobs:
  deploy_website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      # 1. تثبيت الحزم (Dependencies) - الانتقال أولاً إلى مجلد demo
      - name: Install dependencies
        run: |
          cd demo # الانتقال إلى المجلد الذي يحوي package.json
          npm install

      # 2. بناء الموقع (Build) - الانتقال أولاً إلى مجلد demo
      - name: Build website
        run: |
          cd demo # الانتقال إلى المجلد الذي يحوي package.json
          npm run build # يتم تشغيل سكريبت البناء لإنشاء مجلد 'build'

      # 3. استخدام أداة النشر الرسمية لـ Firebase
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          # يجب استبدال هذا بمعرّف مشروعك الحقيقي
          projectId: ascend-bf5b2 
          channelId: live
          # البحث عن firebase.json في مجلد demo
          entryPoint: "./demo"
